# Generated by Django 5.1.5 on 2025-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="digital_file",
            field=models.FileField(
                blank=True, null=True, upload_to="digital_products/"
            ),
        ),
    ]
